---
title: "Data Visualization"
format: html
---

```{r}

library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(forcats)

library(leaflet)
library(DT)
library(scales)
library(janitor)
library(viridis)
```

```{r}
delta_visits <- read_csv("https://portal.edirepository.org/nis/dataviewer?packageid=edi.587.1&entityid=cda8c1384af0089b506d51ad8507641f") %>% 
  janitor::clean_names() ## Introducing this new package!

```

```{r}

glimpse(delta_visits)
range(delta_visits$date)
unique(delta_visits$time_of_day)
dput(colnames(delta_visits))

```

```{r}

visits_long <- delta_visits %>% 
  pivot_longer(cols = c("sm_boat", "med_boat", "lrg_boat", "bank_angler", "scientist", "cars"), 
               names_to = "visitor_type", values_to = "quantity") %>% 
  rename(restore_loc = eco_restore_approximate_location) %>% 
  select(-notes)

```

```{r}

# ggplot(visits_long, aes(x = reorder(visitor_type, -quantity), y = quantity)) + 
#          geom_bar(stat = "identity") + theme_bw()

ggplot(visits_long, aes(x = reorder(restore_loc, -quantity), y = quantity)) + 
         geom_bar(stat = "identity") + theme_bw() + theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

## Calculate daily visits by visit type

```{r}

daily_visit <- visits_long %>% group_by(restore_loc, date, visitor_type) %>% 
  summarise(daily_visits = sum(quantity))

ggplot(daily_visit, aes(x = reorder(restore_loc, -daily_visits), y = daily_visits)) + 
         geom_col(stat = "identity") + theme_bw() + theme(axis.text.x = element_text(angle = 45, hjust = 1))

```
## Customizing our plot

```{r}

ggplot(daily_visit, aes(x = reorder(restore_loc, -daily_visits), y = daily_visits)) + 
         geom_col(stat = "identity", fill = "aquamarine4") + theme_bw() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}

ggplot(daily_visit, aes(x = restore_loc, y = daily_visits, fill = visitor_type)) +
  geom_col() +
  labs(x = "Restoration Locations", y = "Number of Visits",
       fill = "Type of visitor", Title = "Total number of visits to Delta Restoration sites by visitor type",
       subtitle = "Sum of all visits during study period") +
  coord_flip() + theme_classic()

```

## using 'theme() function to further customize our plot

```{r}
ggplot(daily_visit, aes(x = restore_loc, y = daily_visits, fill = visitor_type)) +
  geom_col() +
  labs(x = "Restoration Locations", y = "Number of Visits",
       fill = "Type of visitor", Title = "Total number of visits to Delta Restoration sites by visitor type",
       subtitle = "Sum of all visits during study period") +
  coord_flip() + theme_bw() +
  theme(legend.position = "bottom", axis.ticks.y = element_blank())

```
## Saving theme into an object

```{r}

my_theme <- theme_bw(base_size = 16) + theme(legend.position = "bottom", axis.ticks.y = element_blank())

```

```{r}

ggplot(daily_visit, aes(x = restore_loc, y = daily_visits, fill = visitor_type)) +
  geom_col() +
  labs(x = "Restoration Locations", y = "Number of Visits",
       fill = "Type of visitor", Title = "Total number of visits to Delta Restoration sites by visitor type",
       subtitle = "Sum of all visits during study period") +
  coord_flip() + my_theme + scale_y_continuous(breaks = seq(0,120, 20))

```
```{r}
daily_visit_total <- daily_visit %>% group_by(restore_loc) %>% mutate(n = sum(daily_visits)) %>% ungroup()

ggplot(daily_visit_total, aes(x = reorder(restore_loc, n), y = daily_visits, fill = visitor_type)) +
  geom_col() +
  labs(x = "Restoration Locations", y = "Number of Visits",
       fill = "Type of visitor", Title = "Total number of visits to Delta Restoration sites by visitor type",
       subtitle = "Sum of all visits during study period") +
  coord_flip() + my_theme + scale_y_continuous(breaks = seq(0,120, 20)) +
  scale_fill_viridis_d(option = "C")

```
```{r}

ggsave("figures/visit_restore_sites_delta.jpg", width = 12, height = 6, units = "in")

```

## Creating multiple plots with 'facet_wrap()

```{r}

ggplot(daily_visit_total, aes(x = visitor_type, y = daily_visits, fill = visitor_type)) +
  geom_col() +
  labs(x = "Restoration Locations", y = "Number of Visits",
       fill = "Type of visitor", Title = "Total number of visits to Delta Restoration sites by visitor type",
       subtitle = "Sum of all visits during study period") + theme_bw(base_size = 16) +
  theme(legend.position = "bottom", axis.ticks.x = element_blank(), axis.text.x = element_blank()) +
  scale_y_continuous(breaks = seq(0,120, 20)) + 
  scale_fill_viridis_d(option = "C") + facet_wrap(~restore_loc, nrow = 2)

```
##Interactive tables with 'DT'

```{r}

locations <- visits_long %>% distinct(restore_loc, .keep_all = T) %>% select(restore_loc, latitude, longitude)


```

```{r}
datatable(locations)
```

## interactive map with 'Leaflet

```{r}
leaflet(locations) %>% addTiles() %>% addMarkers(~longitude, ~latitude, popup = ~restore_loc)
```