---
title: "Delta vulnerability map"
author: "Eric"
date: "2023-10-24"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(dplyr)
library(leaflet) # interactive maps
library(plotly) # interactive plots
library(sf)
library(tidycensus)
library(htmltools)
```

```{r, echo = F, results = "hide"}

site <- read.csv("C:/Users/eholmes/Documents/Spatial/NCEAS_restoration/data/spatial/ecoatlas_demo/ecoatlas_demo/ecoatlas_9522/ecoatlas_9522/sites/site.csv")

site_sf <- st_as_sf(site, wkt = "geom")

legal_eco <- read_sf("C:/Users/eholmes/Documents/Spatial/NCEAS_restoration/data/spatial/Vector/Delta_legal_eco_boundary/Delta_legal_eco_boundary/bay-delta_LegalEco_boundary.shp")

frp <- read_sf("C:/Users/eholmes/Documents/Spatial/NCEAS_restoration/data/spatial/Vector/Eco_restore_polygons.shp")

# Removing Yolo Bypass
frp <- frp[frp$Total_Site < 17000,] 

# Download Census data
delta_tracts_wide <- get_acs(
  state = "CA",
  county = c("Alameda", "Contra Costa",
             "Marin", "Napa",
             "Sacramento", "San Francisco", 
             "San Joaquin", "San Mateo", "Santa Clara",
             "Solano", "Sonoma","Yolo"),
  geography = "tract",
  variables = c("B19013_001","B01002_001", "B25071_001", "B25064_001"),
  geometry = TRUE,
  year = 2020,
  output = "wide"
)

colnames(delta_tracts_wide) <- c("GEOID", "NAME", "Median_income", "B19013_001M", "Median_age", 
"B01002_001M", "Median_gr_as_%_of_income", "B25071_001M", "Median_gross_rent", "B25064_001M", 
"geometry")

legal_eco_nad83 <- st_transform(legal_eco, st_crs(delta_tracts_wide))

delta_tracts_wide <- delta_tracts_wide[lengths(st_intersects(delta_tracts_wide, legal_eco_nad83))>0,]

delta_tracts_wide_utm <- st_transform(delta_tracts_wide, crs = st_crs(frp))

frp_wide_join <- st_join(frp, delta_tracts_wide_utm, largest = T)

frp_num <- sf::st_drop_geometry(frp_wide_join[,c(26,28,30,32)])
frp_num <- frp_num[complete.cases(frp_num),]

frp_pca <- prcomp(frp_num, scale. = TRUE)

frp_wide_join_wgs <- st_transform(frp_wide_join, crs = '+init=EPSG:4326')

lookup <- data.frame(var = c("B01002_001", "B19013_001", 
                             "B25064_001", "B25071_001"),
                     varname = c("Median_age", "Median_income", 
                                 "Median_gross_rent", "Median_gr_as_%_of_income"))

```

Row {data-height=500}
-------------------------------------

### Map
```{r}

pal.income <- colorNumeric(
  palette = c("darkgreen","lemonchiffon", "brown"),
  domain = delta_tracts_wide$Median_income)

pal.age <- colorNumeric(
  palette = c("darkgreen","lemonchiffon", "brown"),
  domain = delta_tracts_wide$Median_age)

leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron, group = "Toner") %>%
  addProviderTiles("Esri.WorldImagery", group = "Imagery") %>% 
  addPolygons(data = delta_tracts_wide, 
              group = "Median income", 
              color = ~pal.income(Median_income), 
              fillColor = ~pal.income(Median_income), 
              weight = 1, fillOpacity = .8) %>%  
  addPolygons(data = delta_tracts_wide, 
              group = "Median age", 
              color = ~pal.age(Median_age), 
              fillColor = ~pal.age(Median_age), 
              weight = 1, fillOpacity = .8) %>%  
  addPolygons(data = legal_eco_nad83, color = "black", 
              fillOpacity = 0, weight = 1) %>% 
  addPolygons(data = frp_wide_join_wgs, 
              group = "FRP", label = ~htmlEscape(Name),
              color = "black", fillColor = NULL,
              weight = 1) %>% 
  
  addLayersControl(
    baseGroups = c("Toner", "Imagery"),
    overlayGroups = c("FRP", "Median income", "Median age"),
    options = layersControlOptions(collapsed = FALSE))

```
Row {data-height = 500}
-----------------------------------------------------
```{r}
benefits <- data.frame(SV = c(rep("Disadvantaged",6),rep("Non-disadvantaged",6)),
                       variable = rep(c("Flood protection", "Education",
                                        "Workforce Devlopment", "Recreation",
                                        "Wildlife habitat", "Water quality"), 2, each = T),
                       value = c(80, 60, 75, 60, 95, 45,
                                 70, 80, 65, 61, 90, 60))

plotly::ggplotly(ggplot(benefits, aes(x = variable, y = value, fill = SV)) + 
                   geom_bar(stat = "identity", position = "dodge") + 
                   coord_flip() +
                   labs(y = "Score", x = NULL, title = "Benefits") +
                   theme(legend.position = "bottom") + theme_bw())

```

```{r}
set.seed(1)
grants_ts <- data.frame(x = 1995:2021,
                        y = runif(n = 27, min = 0, max = 100))

plotly::ggplotly(ggplot(grants_ts, aes(x = x, y = y)) + geom_bar(stat = "identity") +
  labs(x = "Year", y = "Project acreage/1000") + theme_bw())

```


Row {data-height = 500}
-----------------------------------------------------------------------

<!--When we use the orientation "rows" we specify each row using "Row".
    To adjust the size of the row use the attribute {data-height=xxx}-->

### PCA biplot

```{r}
biplot(frp_pca)
```

### Corrplot

```{r}
corrplot::corrplot(cor(frp_num), type = "upper", method = "number")
```
