---
title: "functions"
format: html
---
```{r}
library(roxygen2)
(celsius)fahr - 32)*5/9

```

```{r}
#' convert celcius to fahr
#' @param fahr Temp in degrees celcius
#' @return temperature in degree fahrenheit
#' @export
#' @examples
#' @examples 
#' celcius_to_celcius(32)
celcius_to_fahr <- function(celsius){
fahr <- celsius*9/5 + 32
return(fahr)
}

```

## Exploring time saving functions

```{r}
convert_temps <- function(fahr){
  celsius <- (fahr - 32)*5/9
  kelvin <- celsius + 273.15
  return(list(fahr=fahr, celcius=celsius, kelvin=kelvin))
}

temps_df <- data.frame(convert_temps(seq(-100,100,10)))
temps_df



```

# Custom theme

```{r}

custom_theme <- function(base_size = 9){
  ggplot2::theme(text = ggplot2::element_text(family = "Helvetica", color = "grey30", size = base_size),
                 plot.title = ggplot2::element_text(size = ggplot2::rel(1.25), hjust = 0.5, face = 'bold'))
}

library(ggplot2)

ggplot(temps_df, aes(x = fahr, y = celcius, color = kelvin)) + geom_point() + custom_theme(20)

```
## scatterplot_function

```{r}

scatterplot <- function(df, point_size = 2, font_size){
  ggplot(df, mapping = aes(x = fahr, y = celcius, color = kelvin)) + 
    geom_point(size = point_size) +
    custom_theme(font_size)  
}

scatterplot(temps_df, 3, 18)

```