---
title: "Parallel"
output: html_document
date: "2023-10-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(palmerpenguins)
library(dplyr)
library(tidyr)
```

##load data
```{r}
penguins <- palmerpenguins::penguins
```

```{r}

bill_length <- penguins %>% 
  select(species, bill_length_mm) %>% 
  drop_na() %>% 
  as.data.frame()
  
```

# Loop for bootstrapping

```{r}

trials <- 3000
res <- data.frame()

# Sys.time({
  trial <- 1
  while (trial <= trials) {
    index <- sample(100, 100, replace = T)
    result1 <- glm(bill_length[index, 1]~bill_length[index,2], family = binomial(logit))
    r <- coefficients(result1)
    res <- rbind(res, r)
    trial <- trial + 1}
# })

```

```{r}

boot_fx <- function(trial){
  index <- sample(100, 100, replace = T)
    result1 <- glm(bill_length[index, 1]~bill_length[index,2], family = binomial(logit))
    r <- coefficients(result1)
    res <- rbind(data.frame(), r)
}

trials <- seq(1:3000)
system.time({
  results <- lapply(trials, boot_fx)
})

```

# parallelize with mclapply

```{r}

library(parallel)
numCores <- detectCores()

system.time({
  res_mca <- mclapply(trials, boot_fx, mc.cores = numCores/5)
})


```

# Foreach as a looping model

```{r}
library(foreach)

foreach(i = 1:3) %do% {
  sqrt(i)
}

```
```{r}
library(doParallel)
registerDoParallel(numCores/3)
foreach(i=1:3, .combine = rbind) %dopar% {
  sqrt(i)
}

```

```{r}

num_trials = 3000

system.time({
  r <- foreach(icount(num_trials), .combine = rbind) %dopar% {
    index <- sample(100, 100, replace = TRUE)
    result1 <- glm(bill_length[index,1] ~ bill_length[index,2], family = binomial(logit))
    coefficients(result1)
  }
})

stopImplicitCluster()

```

# Future and furrr

```{r}

library(future)
plan(multisession)

f <- future({
  cat("Hello world!\n")
  6.28
})


v <- value(f)
v
```
```{r}
plan(multisession)

download_data <- function(){
  Sys.sleep(0.5)
  return(c(1,2,3))
}

run_model <- function(){
  Sys.sleep(0.5)
  return(42)
}

model_result <- future({
  d <- download_data()
  result <- run_model(d)
  result
})

while(!resolved(model_result)){
  cat("Waiting for model to complete...\n")
  Sys.sleep(.2)
  cat("Do some more work, like refresh another graph\n")
}

```
# purrr and furrr

```{r}

library(purrr)

system.time({
  res_purr <- map(trials, boot_fx)
  })

library(furrr)

plan(multisession, workers = 8)

system.time({
  res_furrr <- future_map(trials, boot_fx, .options = furrr_options(seed = TRUE))
})

```


